GET http://localhost:8080/orders/2994d31e-4f94-43fe-ac58-fd65586cc449



POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "quantity": 5,
      "article": "Dauerlutscher",
      "price": 3.7
    }
  ]
}

###

GET http://localhost:8080/orders

###


### Should work

PUT http://localhost:8080/orders/2994d31e-4f94-43fe-ac58-fd65586cc449/cancel

### Should return 409 Conflict cause order is in the wrong state

PUT http://localhost:8080/orders/8ca418ff-03f1-4fa7-8968-792d6c682a6e/cancel



